spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://54.169.131.163:3306/meou
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: meou@12345

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
